ProyectoWeb3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ProyectoWeb3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Mundial()
        {
            return View();
        }

        public IActionResult Contacto()
        {
            return View();
        }

        public IActionResult ChatBot()
        {
            return View();
        }

    }
}

ProyectoWeb3/Controllers/PartidoController.cs
using Entidades.Entidades;
using Logica.Servicios;
using Microsoft.AspNetCore.Mvc;

namespace ProyectoWeb3.Controllers
{
    public class PartidoController : Controller
    {
        public IPartidoService _partidoController { get; set; }
        public IUsuarioService _usuarioService { get; set; }
        public PartidoController(IPartidoService partidoService, IUsuarioService usuarioService)
        {
            _partidoController = partidoService;
            _usuarioService = usuarioService;
        }

        [HttpGet]
        public IActionResult CrearPartido()
        {
            ViewBag.SeleccionesClasificadas = _partidoController.ObtenerSeleccionesClasificadas();
            return View();
        }

        [HttpPost]
        public IActionResult CrearPartido(Partido partido)
        {
            if(partido.IdSeleccion1 == partido.IdSeleccion2)
            {
                ViewBag.SeleccionesClasificadas = _partidoController.ObtenerSeleccionesClasificadas();
                ViewBag.Error = "Las selecciones ingresadas no pueden enfrentarse ya que son la misma";
                return View(partido);
            }
            Usuario usuario = _usuarioService.GetUsuarioPorEmail(HttpContext.Session.GetString("Email"));

            if(usuario==null)
            {
                _partidoController.Crear(partido);
                return Redirect("/Partido/Predicciones");
            }
            _partidoController.Crear(partido,usuario);
            return Redirect("/Partido/Predicciones");
        }

        /*
        public IActionResult Predicciones()
        {
            ViewBag.SeleccionesClasificadas = _partidoController.ObtenerSeleccionesClasificadas();
            return View(_partidoController.Listar());
        }
        */

        public IActionResult Predicciones(int id)
        {
            Usuario usuario = _usuarioService.GetUsuarioPorEmail(HttpContext.Session.GetString("Email"));

            if (id == 2 & usuario!=null) 
            {
                
                ViewBag.SeleccionesClasificadas = _partidoController.ObtenerSeleccionesClasificadas();
                return View(_partidoController.Filtrar(usuario));
            }
            if (id == 2 & usuario == null ) {
                TempData["error"] = "No se inició sesión";
                ViewBag.SeleccionesClasificadas = _partidoController.ObtenerSeleccionesClasificadas();
                return View(_partidoController.Listar());
            }
            ViewBag.SeleccionesClasificadas = _partidoController.ObtenerSeleccionesClasificadas();
            return View(_partidoController.Listar());
        }

    }
}

ProyectoWeb3/Controllers/UsuarioController.cs
using Entidades.Entidades;
using Logica.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;


namespace ProyectoWeb3.Controllers
{
    public class UsuarioController : Controller
    {
        public IUsuarioService _usuarioController { get; set; }
        public UsuarioController(IUsuarioService usuarioService)
        {
            _usuarioController = usuarioService;
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(Usuario usuario)
        {
            if (!ModelState.IsValid)
                return View(usuario);

            if(_usuarioController.ValidateUsuarioRegistrado(usuario) != null) 
            {
                ViewBag.Error = "El usuario ingresado ya existe";
                return View(usuario);
            }

            _usuarioController.Registrar(usuario);
            return Redirect("/Usuario/Usuarios");


        }

        [HttpGet]
        public IActionResult Usuarios()
        {
            return View(_usuarioController.Listar());
        }

        [HttpGet]
        public IActionResult PerfilUsuario()
        {
            if(string.IsNullOrEmpty(HttpContext.Session.GetString("Email")))
            {
                return Redirect("/Home/Index");
            }

            ViewBag.Email = HttpContext.Session.GetString("Email");
            return View();
            
        }

        [HttpGet]
        public IActionResult IniciarSesion()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IniciarSesion(Usuario usuario)
        {
            if (!ModelState.IsValid)
                return View(usuario);

            if (_usuarioController.GetUsuario(usuario) == null)
            {
                ViewBag.Error = "Las credenciales ingresadas no son validas";
                return View(usuario);
            }

            HttpContext.Session.SetString("Email", usuario.Email);
            return Redirect("/Home/Index");
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.SetString("Email", "");
            return Redirect("/Home/Index");
        }
    }
}

ProyectoWeb3/Views/Home/ChatBot.cshtml
@{
    ViewData["Title"] = "ChatBot";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $.ajax({
        type: "GET",
        url: "https://webchat.botframework.com/api/tokens",
        headers: {
            Authorization:
                "BotConnector BsN-yzjNPCM.GuiJKDbtmATdIslQWAgHBpQEzB8y5Io5r5ilBpdEgXA",
        },
        success: function (result) {
            console.log(result);
            let token = result.replace('"', '')
            console.log(token)
            let iframe = '<iframe src="https://webchat.botframework.com/embed/newResource?t=' + token + '" style="min-width: 400px; width: 100%; min-height: 400px"></iframe>'
            $("#bot").append(iframe)
        },
        error: function (result) {
            //handle the error
        },
    });
</script>

<div class="w-100 d-flex justify-content-start align-items-center shadow" id="fondo-registro">
    <div class="d-flex flex-column justify-content-end p-3 w-50 bg-white border-1 rounded h-75" style="margin-left:5%;">
        <div id="bot" style='min-width: 400px; width: 100%; min-height: 400px;'></div>
    </div>
</div>

<style>
    #fondo-registro{
        height:91vh;
        background-image: url("../images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }
   #webchat{
        height: 90% !important;
    }


</style>

ProyectoWeb3/Views/Home/Contacto.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Contacto";
}

<div id="fondo-contacto" class="d-flex justify-content-start align-items-center">
    <div class="d-flex flex-column justify-content-around bg-white rounded border-1 w-50 p-3 shadow" style="margin-left:5%;">
        <h1>Contacto</h1>
        <form>
            <div class="mb-3">
                Motivo
                <select class="form-control">
                    <option disabled selected>Elegir una opcion..</option>
                    <option>Sugerencia</option>
                    <option>Reclamo</option>
                    <option>Otro</option>
                </select>
                @*<span asp-validation-for="Email"></span>*@
            </div>
            <div class="mb-3">
                Asunto
                <input type="text" class="form-control">
                @*<span asp-validation-for="Password"></span>*@
            </div>
            <div class="mb-3">
                Descripcion
                <textarea class="form-control" rows="3"></textarea>
                @*<span asp-validation-for="Password"></span>*@
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>

    </div>
</div>

<style>
    #fondo-contacto {
        height:91vh;
        background-image: url("../images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }
</style>

ProyectoWeb3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="d-flex align-content-center p-3" id="index">
    <div class="w-50 d-flex flex-column justify-content-center mb-4" style="margin-left:5%;">
        <h1 class="display-4 h1 text-white fw-bold">Cuenta Regresiva para Catar 2022</h1>
        <p class="text-white p">
            En la cuenta atrás para el comienzo de la cita mundialista en Catar,
            el 20 de noviembre, FIFA+ presenta 100 de los mejores momentos de la historia
            de la Copa Mundial de la FIFA.
        </p>
        <a class="btn btn-primary w-25" asp-area="" asp-controller="Home" asp-action="Mundial">Leer más</a>
    </div>

</div>

<style>
    .w-60{
        width: 60%;
    }
    #index{
        height:91vh;
        background-image: url("../images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }
    h1{
        text-shadow: 0 2px 2px 2px black;
    }
</style>

ProyectoWeb3/Views/Home/Mundial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Mundial";
}

<div id="fondo-mundial" class="d-flex justify-content-start align-items-center">
    <div class="d-flex flex-column justify-content-around bg-white rounded border-1 w-50 p-3" style="margin-left:5%;">
        <h1>Copa Mundial de Futbol</h1>

            <p>La Copa Mundial de la FIFA, también conocida como Copa Mundial de Fútbol, Copa del Mundo o simplemente Mundial,
            cuyo nombre original fue Campeonato Mundial de Fútbol, es el principal torneo internacional oficial de fútbol
            masculino a nivel de selecciones nacionales en el mundo.n 1​
            Este evento deportivo se realiza cada cuatro años desde 1930, con la excepción de 1942 y 1946,
            en los que se suspendió respectivamente debido al desarrollo y las consecuencias de la Segunda Guerra Mundial. Cuenta con dos etapas principales
            : un proceso clasificatorio en el que participan en la actualidad cerca de 200 selecciones nacionales y una fase final realizada cada cuatro años
            en una sede definida con anticipación en la que participan 32 equipos (48 a partir de la edición de 2026) durante un periodo cercano a un mes.
            El balón oficial es fabricado por la compañía alemana de equipamiento deportivo Adidas.</p>
            
            <p>La fase final del torneo es el evento deportivo de una sola disciplina más importante del mundo (la final de la Copa Mundial de
            Fútbol de 2002 fue vista por más de 1100 millones de personas),1​ y el segundo más importante a nivel general después de los Juegos
            Olímpicos.</p>

            <p>Ha sido realizada en 21 ocasiones, en las que ocho «países futbolizados» —corresponden a las potencias mundiales históricas y candidatos
            — han alzado la copa: Brasil es la selección más exitosa, con cinco victorias; Alemania e Italia le siguen con cuatro trofeos; Argentina,
            Francia y Uruguay la han ganado dos veces, en tanto Inglaterra y España se han titulado campeones una vez.n 2​ Los equipos europeos han
            ganado el título en doce ocasiones, mientras que los sudamericanos lo han hecho en nueve. Solo dos equipos de otras confederaciones han
            llegado a semifinales: Estados Unidos en 1930 y Corea del Sur en 2002.</p>
    </div>
</div>

<style>
    #fondo-mundial{
        height:91vh;
        background-image: url("../images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }

    #fondo-mundial p{
        font-size: 0.8em;
        font-style: italic;
    }
</style>

ProyectoWeb3/Views/Partido/CrearPartido.cshtml
@using Entidades.Entidades

@model Entidades.Entidades.PartidoModelMetaData

@{
    ViewData["Title"] = "Crear Partido";
}

<div class="w-100 d-flex justify-content-start align-items-center shadow" id="fondo-registro">
    <div class="d-flex flex-column justify-content-around p-3 w-50 bg-white border-1 rounded" style="margin-left:5%;">
        <h1>Prediccion del partido</h1>
        <form action="/Partido/CrearPartido" method="post">
          @*<div class="mb-3">
                Grupo
                <select class="form-control" @*name="" asp-for="">
                    <option>A</option>
                </select>
                <span asp-validation-for="Email"></span>
            </div>*@
            <div class="mb-3">
                Seleccion 1
                <select class="form-control" name="IdSeleccion1" asp-for="IdSeleccion1">
                    @foreach (Seleccion seleccion in ViewBag.SeleccionesClasificadas)
                    {
                        <option value="@seleccion.IdSeleccion">@seleccion.Seleccion1</option>
                    }
                </select>
                <span asp-validation-for="IdSeleccion1" class="text-danger"></span>
            </div>
            <div class="mb-3">
                Goles
                <input type="number" class="form-control" name="GolesSeleccion1" asp-for="GolesSeleccion1" />
                <span asp-validation-for="GolesSeleccion1" class="text-danger"></span>
            </div>
            <div class="mb-3">
                Seleccion 2
                <select class="form-control" name="IdSeleccion2" asp-for="IdSeleccion2">
                    @foreach (Seleccion seleccion2 in ViewBag.SeleccionesClasificadas)
                    {
                        <option value="@seleccion2.IdSeleccion">@seleccion2.Seleccion1</option>
                    }
                </select>
                <span asp-validation-for="IdSeleccion2" class="text-danger"></span>
                
            </div>
            <div class="mb-3">
                Goles
                <input type="number" class="form-control" name="GolesSeleccion2" asp-for="GolesSeleccion2" />
                <span asp-validation-for="GolesSeleccion2" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <span class="text-danger">@ViewBag.Error</span>
            </div>
            <input type="submit" class="btn btn-primary" value="Crear" />
        </form>
    </div>
</div>

<style>
    #fondo-registro {
        height: 91vh;
        background-image: url("../images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }
</style>

ProyectoWeb3/Views/Partido/Predicciones.cshtml
@using Entidades.Entidades
@model List<Entidades.Entidades.Partido>

@{
    ViewData["Title"] = "Predicciones";
}

<div id="fondo-resultados-prode" class="d-flex justify-content-start align-items-center">
    <div class="d-flex flex-column justify-content-around p-3 w-50 bg-white border-1 rounded" style="margin-left:5%;">
        <h2 class="">Predicciones mundialistas</h2>
        <div class="dropdown mb-3">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Filtrar por
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="/Partido/Predicciones/1">Todas las predicciones</a></li>
                <li><a class="dropdown-item" href="/Partido/Predicciones/2">Mis predicciones</a></li>
            </ul>
            <div class="mt-2">
                <span class="text-danger">@TempData["error"]</span>
            </div>
        </div>
        <table class="table py-3 bg-white border rounded shadow w-100 p-2">
            <tr>
                <th class="text-center" scope="col">Id Partido</th>
                <th class="text-center" scope="col">Seleccion 1</th>
                <th class="text-center" scope="col">Goles</th>
                <th class="text-center" scope="col">-</th>
                <th class="text-center" scope="col">Goles</th>
                <th class="text-center" scope="col">Seleccion 2</th>
                <th class="text-center" scope="col">Usuario</th>
            </tr>
            @foreach (var partido in Model)
            {
                <tr scope="row">
                    <td class="text-center">
                        @partido.IdPartido
                    </td>
                    <td class="text-center">
                        @foreach (var seleccion in ((List<Seleccion>)ViewBag.SeleccionesClasificadas).Where(s => s.IdSeleccion == partido.IdSeleccion1))
                        {
                            @seleccion.Seleccion1;
                        }
                    </td>
                    <td class="text-center">
                        @partido.GolesSeleccion1
                    </td>
                    <td class="text-center">
                        -
                    </td>
                    <td class="text-center">
                        @partido.GolesSeleccion2
                    </td>
                    <td class="text-center">
                        @foreach (var seleccion in ((List<Seleccion>)ViewBag.SeleccionesClasificadas).Where(s => s.IdSeleccion == partido.IdSeleccion2))
                        {
                            @seleccion.Seleccion1
                            ;
                        }
                    </td>
                    <td class="text-center">
                        @partido.Usuario
                    </td>
                </tr>
            }
        </table>
        <a asp-area="" asp-controller="Partido" asp-action="CrearPartido" class="btn btn-primary text-white w-25 mb-2">
            Crear Partido
        </a>
    </div>
</div>

<style>
    #fondo-resultados-prode {
        height:91vh;
        background-image: url("/images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }
</style>

ProyectoWeb3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoWeb3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoWeb3.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css" />
</head>
<body class="d-flex">
    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;" id="menu">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <img src="~/images/Qatar2022.png" height="35" width="35" />
            <h2 class="fw-bolder">Futbolizados</h2>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto" id="nav-lateral">
            <li>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link text-white" aria-current="page">
                    <i class="fi fi-rr-home"></i>
                    Home
                </a>
            </li>
            <li>
                <a asp-area="" asp-controller="Home" asp-action="Mundial" class="nav-link text-white">
                    <i class="fi fi-rr-trophy"></i>
                    Copa del Mundo
                </a>
            </li>
            <li>
                <a asp-area="" asp-controller="Partido" asp-action="Predicciones" class="nav-link text-white">
                    <i class="fi fi-rr-list-check"></i>
                    Predicciones
                </a>
            </li>
            <li>
                <a asp-area="" asp-controller="Home" asp-action="Contacto" class="nav-link text-white">
                    <i class="fi fi-rr-users"></i>
                    Contacto
                </a>
            </li>
            <li>
                <a asp-area="" asp-controller="Home" asp-action="ChatBot" class="nav-link text-white">
                    <i class="fi fi-rr-envelope"></i>
                    ChatBot
                </a>
            </li>
        </ul>
        <hr>
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fi fi-rr-portrait m-1"></i>
                <p class="m-1">Usuario</p>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Registrar">Registrarse</a></li>
                <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="IniciarSesion">Iniciar Sesion</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="PerfilUsuario">Perfil</a></li>
                <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Logout">Cerrar Sesion</a></li>
            </ul>
        </div>
    </div>
    
    <div class="w-100" id="contenedor-render">

        <div id="contenedor-body">
            <main role="main">
                @RenderBody()
            </main>
        </div>

        <footer class="d-flex flex-wrap justify-content-around align-items-center border-top">
            <div class="d-flex align-items-center">
                <span class="text-muted">&copy; Universidad Nacional de la Matanza - Programacion Web 3</span>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <partial name="/Views/Shared/_ValidationScriptsPartial.cshtml" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>
    body{
        margin: 0 !important;
    }
    footer{
        margin: 0 !important;
        padding-top: 0!important;
    }
    #menu{
        height: 100vh;
        position: fixed;
        top: 0;
        left: 0;
    }
    #contenedor-render{
        position: absolute;
        top: 0;
        left: 280px;
        width: calc(100vw - 298px) !important;
    }
    #contenedor-body{
        height: 91vh;
    }
    footer{
        height: 8vh;
        margin-top:1vh;
    }
    #nav-lateral li:hover{
        background-color: #0d6efd;
        border-radius: 5px;
    }
</style>

ProyectoWeb3/Views/Usuario/IniciarSesion.cshtml
@model Entidades.Entidades.UsuarioModelMetaData

@{
    ViewData["Title"] = "Iniciar Sesion";
}

<div class="w-100 d-flex justify-content-start align-items-center shadow" id="fondo-login">
    <div class="d-flex flex-column justify-content-around p-3 w-50 bg-white border-1 rounded" style="margin-left:5%;">
        <h1>Welcome back!</h1>
        <form action="/Usuario/IniciarSesion" method="post">
            <div class="mb-3">
                Email
                <input type="email" class="form-control" name="Email" asp-for="Email">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                Contraseña
                <input type="password" class="form-control" name="Contraseña" asp-for="Contraseña">
                <span asp-validation-for="Contraseña" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <span class="text-danger">@ViewBag.Error</span>
            </div>
            <input type="submit" class="btn btn-primary" value="Iniciar Sesion"/>
        </form>
    </div>
</div>

<style>
    #fondo-login {
        height:91vh;
        background-image: url("../images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }
</style>

ProyectoWeb3/Views/Usuario/PerfilUsuario.cshtml
@model Entidades.Entidades.UsuarioModelMetaData
@{
    ViewData["Title"] = "Perfil";
}

<div id="fondo-perfil" class="d-flex align-items-center">
    <div class="d-flex flex-column justify-content-around p-3 w-50 bg-white border-1 rounded" style="margin-left:5%;">
        <h2>Mis Datos</h2>
        <p>Email: @ViewBag.Email</p>
        <p>Contraseña: ******</p>
    </div>

</div>

<style>
    #fondo-perfil {
        height:91vh;
        background-image: url("../images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }
</style>

ProyectoWeb3/Views/Usuario/Registrar.cshtml
@model Entidades.Entidades.UsuarioModelMetaData

@{
    ViewData["Title"] = "Registro";
}

<div class="w-100 d-flex justify-content-start align-items-center shadow" id="fondo-registro">
    <div class="d-flex flex-column justify-content-around p-3 w-50 bg-white border-1 rounded" style="margin-left:5%;">
        <h1>Bienvenido a Futbolizados!</h1>
        <form action="/Usuario/Registrar" method="post">
            <div class="mb-3">
                Email
                <input type="email" class="form-control" name="Email" asp-for="Email">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                Contraseña
                <input type="password" class="form-control" name="Contraseña" asp-for="Contraseña">
                <span asp-validation-for="Contraseña" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <span class="text-danger">@ViewBag.Error</span>
            </div>
            <input type="submit" class="btn btn-primary" value="Registrar"/>
        </form>
    </div>
</div>

<style>
    #fondo-registro{
        height:91vh;
        background-image: url("../images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }
</style>

ProyectoWeb3/Views/Usuario/Usuarios.cshtml
@model List<Entidades.Entidades.UsuarioModelMetaData>

@{
    ViewData["Title"] = "Usuarios";
}

<div id="fondo-usuarios" class="d-flex justify-content-center align-items-center">
    <table class="table py-3 bg-white border rounded shadow w-50">
        <tr>
            <th scope="col">idUsuario</th>
            <th scope="col">Email</th>
            <th scope="col">Contraseña</th>
        </tr>
        @foreach (var user in Model)
        {
            <tr scope="row">
                <td>
                    @user.IdUsuario
                </td>
                <td>
                    @user.Email
                </td>
                <td>
                    @user.Contraseña
                </td>
            </tr>
        }
    </table>
</div>

<style>
    #fondo-usuarios {
        height:91vh;
        background-image: url("../images/fondo-index.jpg");
        background-size: cover;
        background-position: 50% 50%;
    }
</style>